Repository warendy/warendy_BE, pull requests merged in 2023-08, with the labels that each got.

#26 통행 게시글 TEST CODE 추가
  src/main/java/com/be/friendy/warendy/domain/board/controller/BoardController.java
  src/main/java/com/be/friendy/warendy/domain/board/dto/response/BoardSearchResponse.java
  src/main/java/com/be/friendy/warendy/domain/board/service/BoardService.java
  src/main/java/com/be/friendy/warendy/domain/member/repository/MemberRepository.java
  src/main/java/com/be/friendy/warendy/domain/member/service/MemberService.java
  src/main/java/com/be/friendy/warendy/domain/wine/entity/Wine.java
  src/main/java/com/be/friendy/warendy/domain/wine/repository/WineRepository.java
  src/test/java/com/be/friendy/warendy/domain/board/controller/BoardControllerTest.java
  src/test/java/com/be/friendy/warendy/domain/board/service/BoardServiceTest.java
Labels: test

#30 와인 상세 페이지 기능 추가
  src/main/java/com/be/friendy/warendy/domain/review/repository/ReviewRepository.java
  src/main/java/com/be/friendy/warendy/domain/wine/controller/WineController.java
  src/main/java/com/be/friendy/warendy/domain/wine/dto/response/WineDetailSearchResponse.java
  src/main/java/com/be/friendy/warendy/domain/wine/entity/Wine.java
  src/main/java/com/be/friendy/warendy/domain/wine/service/WineService.java
  src/test/java/com/be/friendy/warendy/WarendyBeApplicationTests.java
  src/test/java/com/be/friendy/warendy/domain/wine/controller/WineControllerTest.java
  src/test/java/com/be/friendy/warendy/domain/wine/service/WineServiceTest.java
Labels: enhancement

#36 내 주변 와인바 조회 기능 추가
  src/main/java/com/be/friendy/warendy/domain/winebar/controller/WinebarController.java
  src/main/java/com/be/friendy/warendy/domain/winebar/repository/WinebarRepository.java
  src/main/java/com/be/friendy/warendy/domain/winebar/service/WineBarService.java
  src/test/java/com/be/friendy/warendy/domain/winebar/controller/WinebarControllerTest.java
  src/test/java/com/be/friendy/warendy/domain/winebar/service/WineBarServiceTest.java
Labels: enhancement

#37 wine pairing 바뀐 타입을 수정 및 pairing 오타 수정
  src/test/java/com/be/friendy/warendy/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/be/friendy/warendy/domain/review/service/ReviewServiceTest.java
  src/test/java/com/be/friendy/warendy/domain/wine/controller/WineControllerTest.java
  src/test/java/com/be/friendy/warendy/domain/wine/service/WineServiceTest.java
Labels: bug

#32 양방향 채팅 기능 추가
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/be/friendy/warendy/config/jwt/TokenProvider.java
  src/main/java/com/be/friendy/warendy/domain/chat/configuration/KafkaConfig.java
  src/main/java/com/be/friendy/warendy/domain/chat/configuration/WebSocketConfig.java
  src/main/java/com/be/friendy/warendy/domain/chat/controller/ChatController.java
  src/main/java/com/be/friendy/warendy/domain/chat/dto/MessageDto.java
  src/main/java/com/be/friendy/warendy/domain/chat/entity/ChatClient.java
  src/main/java/com/be/friendy/warendy/domain/chat/entity/ChatRoom.java
  src/main/java/com/be/friendy/warendy/domain/chat/entity/Chatroom.java
  src/main/java/com/be/friendy/warendy/domain/chat/entity/ConnectedChat.java
  src/main/java/com/be/friendy/warendy/domain/chat/entity/Message.java
  src/main/java/com/be/friendy/warendy/domain/chat/entity/Notification.java
  src/main/java/com/be/friendy/warendy/domain/chat/error.md
  src/main/java/com/be/friendy/warendy/domain/chat/repository/ChatClientRepository.java
  src/main/java/com/be/friendy/warendy/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/be/friendy/warendy/domain/chat/repository/MessageRepository.java
  src/main/java/com/be/friendy/warendy/domain/chat/service/ChatService.java
  src/main/java/com/be/friendy/warendy/domain/chat/service/ChatWebSocketHandler.java
  src/main/java/com/be/friendy/warendy/domain/chat/service/WebSocketSessionService.java
  src/main/resources/application.yml
  src/test/java/com/be/friendy/warendy/domain/board/controller/BoardControllerTest.java
Labels: enhancement

#38 불필요한 조건 삭제, 어노테이션 변경, 변수 조건 변경.
  src/main/java/com/be/friendy/warendy/domain/board/service/BoardService.java
  src/main/java/com/be/friendy/warendy/domain/member/service/MemberService.java
  src/main/java/com/be/friendy/warendy/domain/review/service/ReviewService.java
  src/main/java/com/be/friendy/warendy/domain/wine/service/WineService.java
  src/main/java/com/be/friendy/warendy/domain/winebar/service/WineBarService.java
  src/test/java/com/be/friendy/warendy/domain/board/controller/BoardControllerTest.java
  src/test/java/com/be/friendy/warendy/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/be/friendy/warendy/domain/review/service/ReviewServiceTest.java
  src/test/java/com/be/friendy/warendy/domain/wine/controller/WineControllerTest.java
Labels: documentation

#39 wine detail 조회 시 순환 참조 문제 해결.
  src/main/java/com/be/friendy/warendy/domain/wine/dto/response/WineDetailSearchResponse.java
  src/main/java/com/be/friendy/warendy/domain/wine/entity/Wine.java
  src/test/java/com/be/friendy/warendy/domain/wine/controller/WineControllerTest.java
Labels: bug

#43 와인 추천 기능 구현
  src/main/java/com/be/friendy/warendy/domain/wine/controller/WineController.java
  src/main/java/com/be/friendy/warendy/domain/wine/dto/response/RecommendWineResponse.java
  src/main/java/com/be/friendy/warendy/domain/wine/repository/WineRepository.java
  src/main/java/com/be/friendy/warendy/domain/wine/service/WineService.java
  src/test/java/com/be/friendy/warendy/domain/wine/controller/WineControllerTest.java
  src/test/java/com/be/friendy/warendy/domain/wine/service/WineServiceTest.java
Labels: enhancement

#45 feat/#34 삭제 기능 추가, 카테고리 저장 기능 수정, 응답 헤더 값 수정.
  src/main/java/com/be/friendy/warendy/domain/favorite/controller/FavoriteController.java
  src/main/java/com/be/friendy/warendy/domain/favorite/dto/request/GivenWineInfo.java
  src/main/java/com/be/friendy/warendy/domain/favorite/repository/FavoriteRepository.java
  src/main/java/com/be/friendy/warendy/domain/favorite/service/FavoriteService.java
  src/main/java/com/be/friendy/warendy/domain/member/controller/MemberController.java
Labels: enhancement
